// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SistemaComercial.Infrastructure;

#nullable disable

namespace SistemaComercial.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260511081611_AddVentasCursosAlumnos")]
    partial class AddVentasCursosAlumnos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SistemaComercial.Dominio.Alumnos.Alumno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellidos");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ciudad");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("direccion");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombres");

                    b.Property<uint>("version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_alumnos");

                    b.ToTable("alumnos", (string)null);
                });

            modelBuilder.Entity("SistemaComercial.Dominio.Cargos.Cargo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<uint>("version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_cargos");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_cargos_nombre");

                    b.ToTable("cargos", (string)null);
                });

            modelBuilder.Entity("SistemaComercial.Dominio.Cursos.Curso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CantidadHoras")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_horas");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio");

                    b.Property<uint>("version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_cursos");

                    b.ToTable("cursos", (string)null);
                });

            modelBuilder.Entity("SistemaComercial.Dominio.Empleados.Empleado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CargoId")
                        .HasColumnType("uuid")
                        .HasColumnName("cargo_id");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("clave");

                    b.Property<string>("CodigoEmpleado")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("codigo_empleado");

                    b.Property<string>("CorreoEmpresarial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correo_empresarial");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_ingreso");

                    b.Property<uint>("version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_empleados");

                    b.HasIndex("CargoId")
                        .HasDatabaseName("ix_empleados_cargo_id");

                    b.HasIndex("CodigoEmpleado")
                        .IsUnique()
                        .HasDatabaseName("ix_empleados_codigo_empleado");

                    b.HasIndex("CorreoEmpresarial")
                        .IsUnique()
                        .HasDatabaseName("ix_empleados_correo_empresarial");

                    b.ToTable("empleados", (string)null);
                });

            modelBuilder.Entity("SistemaComercial.Dominio.Ventas.DetalleVenta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<Guid>("CursoId")
                        .HasColumnType("uuid")
                        .HasColumnName("curso_id");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total");

                    b.Property<Guid>("VentaId")
                        .HasColumnType("uuid")
                        .HasColumnName("venta_id");

                    b.Property<uint>("version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_detalle_ventas");

                    b.HasIndex("CursoId")
                        .HasDatabaseName("ix_detalle_ventas_curso_id");

                    b.HasIndex("VentaId")
                        .HasDatabaseName("ix_detalle_ventas_venta_id");

                    b.ToTable("detalle_ventas", (string)null);
                });

            modelBuilder.Entity("SistemaComercial.Dominio.Ventas.Venta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AlumnoId")
                        .HasColumnType("uuid")
                        .HasColumnName("alumno_id");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("serie");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total");

                    b.Property<uint>("version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_ventas");

                    b.HasIndex("AlumnoId")
                        .HasDatabaseName("ix_ventas_alumno_id");

                    b.HasIndex("Serie", "Numero")
                        .IsUnique()
                        .HasDatabaseName("ix_ventas_serie_numero");

                    b.ToTable("ventas", (string)null);
                });

            modelBuilder.Entity("SistemaComercial.Dominio.Empleados.Empleado", b =>
                {
                    b.HasOne("SistemaComercial.Dominio.Cargos.Cargo", "Cargo")
                        .WithMany()
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_empleados_cargos_cargo_id");

                    b.OwnsOne("SistemaComercial.Dominio.Empleados.ObjectValue.NombreCompleto", "NombreCompleto", b1 =>
                        {
                            b1.Property<Guid>("EmpleadoId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("ApellidoMaterno")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("nombre_completo_apellido_materno");

                            b1.Property<string>("ApellidoPaterno")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("nombre_completo_apellido_paterno");

                            b1.Property<string>("Nombres")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("nombre_completo_nombres");

                            b1.HasKey("EmpleadoId");

                            b1.ToTable("empleados");

                            b1.WithOwner()
                                .HasForeignKey("EmpleadoId")
                                .HasConstraintName("fk_empleados_empleados_id");
                        });

                    b.OwnsOne("SistemaComercial.Dominio.Empleados.ObjectValue.NumeroDocumento", "NumeroDocumento", b1 =>
                        {
                            b1.Property<Guid>("EmpleadoId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("numero_documento_tipo");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("character varying(12)")
                                .HasColumnName("numero_documento_valor");

                            b1.HasKey("EmpleadoId");

                            b1.ToTable("empleados");

                            b1.WithOwner()
                                .HasForeignKey("EmpleadoId")
                                .HasConstraintName("fk_empleados_empleados_id");
                        });

                    b.OwnsOne("SistemaComercial.Dominio.Empleados.ObjectValue.Salario", "Salario", b1 =>
                        {
                            b1.Property<Guid>("EmpleadoId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Moneda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("salario_moneda");

                            b1.Property<decimal>("Monto")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("salario_monto");

                            b1.HasKey("EmpleadoId");

                            b1.ToTable("empleados");

                            b1.WithOwner()
                                .HasForeignKey("EmpleadoId")
                                .HasConstraintName("fk_empleados_empleados_id");
                        });

                    b.Navigation("Cargo");

                    b.Navigation("NombreCompleto")
                        .IsRequired();

                    b.Navigation("NumeroDocumento")
                        .IsRequired();

                    b.Navigation("Salario")
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaComercial.Dominio.Ventas.DetalleVenta", b =>
                {
                    b.HasOne("SistemaComercial.Dominio.Cursos.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_detalle_ventas_cursos_curso_id");

                    b.HasOne("SistemaComercial.Dominio.Ventas.Venta", null)
                        .WithMany("Detalles")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_detalle_ventas_ventas_venta_id");

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("SistemaComercial.Dominio.Ventas.Venta", b =>
                {
                    b.HasOne("SistemaComercial.Dominio.Alumnos.Alumno", "Alumno")
                        .WithMany()
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ventas_alumnos_alumno_id");

                    b.Navigation("Alumno");
                });

            modelBuilder.Entity("SistemaComercial.Dominio.Ventas.Venta", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
