// <auto-generated />
using System;
using SistemaComercial.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace SistemaComercial.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260430014400_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SistemaComercial.Dominio.Cargos.Cargo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<uint>("version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_cargos");

                    b.ToTable("cargos", (string)null);
                });

            modelBuilder.Entity("SistemaComercial.Dominio.Empleados.Empleado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CargoId")
                        .HasColumnType("uuid")
                        .HasColumnName("cargo_id");

                    b.Property<string>("CodigoEmpleado")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("codigo_empleado");

                    b.Property<string>("CorreoEmpresarial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correo_empresarial");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_ingreso");

                    b.Property<uint>("version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_empleados");

                    b.HasIndex("CargoId")
                        .HasDatabaseName("ix_empleados_cargo_id");

                    b.HasIndex("CodigoEmpleado")
                        .IsUnique()
                        .HasDatabaseName("ix_empleados_codigo_empleado");

                    b.HasIndex("CorreoEmpresarial")
                        .IsUnique()
                        .HasDatabaseName("ix_empleados_correo_empresarial");

                    b.ToTable("empleados", (string)null);
                });

            modelBuilder.Entity("SistemaComercial.Dominio.Empleados.Empleado", b =>
                {
                    b.HasOne("SistemaComercial.Dominio.Cargos.Cargo", "Cargo")
                        .WithMany()
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_empleados_cargos_cargo_id");

                    b.OwnsOne("SistemaComercial.Dominio.Empleados.ObjectValue.NombreCompleto", "NombreCompleto", b1 =>
                        {
                            b1.Property<Guid>("EmpleadoId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("ApellidoMaterno")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("nombre_completo_apellido_materno");

                            b1.Property<string>("ApellidoPaterno")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("nombre_completo_apellido_paterno");

                            b1.Property<string>("Nombres")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("nombre_completo_nombres");

                            b1.HasKey("EmpleadoId");

                            b1.ToTable("empleados");

                            b1.WithOwner()
                                .HasForeignKey("EmpleadoId")
                                .HasConstraintName("fk_empleados_empleados_id");
                        });

                    b.OwnsOne("SistemaComercial.Dominio.Empleados.ObjectValue.NumeroDocumento", "NumeroDocumento", b1 =>
                        {
                            b1.Property<Guid>("EmpleadoId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("numero_documento_tipo");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("character varying(12)")
                                .HasColumnName("numero_documento_valor");

                            b1.HasKey("EmpleadoId");

                            b1.ToTable("empleados");

                            b1.WithOwner()
                                .HasForeignKey("EmpleadoId")
                                .HasConstraintName("fk_empleados_empleados_id");
                        });

                    b.OwnsOne("SistemaComercial.Dominio.Empleados.ObjectValue.Salario", "Salario", b1 =>
                        {
                            b1.Property<Guid>("EmpleadoId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Moneda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("salario_moneda");

                            b1.Property<decimal>("Monto")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("salario_monto");

                            b1.HasKey("EmpleadoId");

                            b1.ToTable("empleados");

                            b1.WithOwner()
                                .HasForeignKey("EmpleadoId")
                                .HasConstraintName("fk_empleados_empleados_id");
                        });

                    b.Navigation("Cargo");

                    b.Navigation("NombreCompleto")
                        .IsRequired();

                    b.Navigation("NumeroDocumento")
                        .IsRequired();

                    b.Navigation("Salario")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
